import { hash } from 'bcryptjs';

import { db, pool } from './client';
import {
  auditLogs,
  customFieldDefinitions,
  stationBrands,
  stationConnectors,
  stationCustomFieldValues,
  stationIssueRecords,
  stationModelConnectorTemplates,
  stationModels,
  stations,
  stationTestHistory,
  users,
} from './schema';

const seed = async () => {
  const adminPasswordHash = await hash('Admin123!', 10);
  const operatorPasswordHash = await hash('Operator123!', 10);

  const adminUserId = '11111111-1111-1111-1111-111111111111';
  const operatorUserId = '22222222-2222-2222-2222-222222222222';

  const customFieldIds = {
    firmwareVersion: 'aaaaaaaa-1111-1111-1111-111111111111',
    coolingType: 'aaaaaaaa-2222-2222-2222-222222222222',
    networkProvider: 'aaaaaaaa-3333-3333-3333-333333333333',
    installationZone: 'aaaaaaaa-4444-4444-4444-444444444444',
    batteryBufferKwh: 'aaaaaaaa-5555-5555-5555-555555555555',
    commissioningDate: 'aaaaaaaa-6666-6666-6666-666666666666',
  } as const;

  const stationIds = {
    s1: 'bbbbbbbb-0000-0000-0000-000000000001',
    s2: 'bbbbbbbb-0000-0000-0000-000000000002',
    s3: 'bbbbbbbb-0000-0000-0000-000000000003',
    s4: 'bbbbbbbb-0000-0000-0000-000000000004',
    s5: 'bbbbbbbb-0000-0000-0000-000000000005',
    s6: 'bbbbbbbb-0000-0000-0000-000000000006',
    s7: 'bbbbbbbb-0000-0000-0000-000000000007',
    s8: 'bbbbbbbb-0000-0000-0000-000000000008',
  } as const;

  const brandIds = {
    vestel: '99999999-0000-0000-0000-000000000001',
  } as const;

  const modelIds = {
    evc02: '99999999-1000-0000-0000-000000000001',
    evc04: '99999999-1000-0000-0000-000000000002',
    evc05: '99999999-1000-0000-0000-000000000003',
    evc06: '99999999-1000-0000-0000-000000000004',
  } as const;

  await db.delete(auditLogs);
  await db.delete(stationIssueRecords);
  await db.delete(stationTestHistory);
  await db.delete(stationCustomFieldValues);
  await db.delete(stationModelConnectorTemplates);
  await db.delete(stationConnectors);
  await db.delete(customFieldDefinitions);
  await db.delete(stations);
  await db.delete(stationModels);
  await db.delete(stationBrands);
  await db.delete(users);

  await db.insert(users).values([
    {
      id: adminUserId,
      email: 'admin@evlab.local',
      fullName: 'Aylin Demir',
      passwordHash: adminPasswordHash,
      role: 'admin',
      isActive: true,
    },
    {
      id: operatorUserId,
      email: 'operator@evlab.local',
      fullName: 'Mert Kaya',
      passwordHash: operatorPasswordHash,
      role: 'operator',
      isActive: true,
    },
  ]);

  await db.insert(customFieldDefinitions).values([
    {
      id: customFieldIds.firmwareVersion,
      key: 'firmware_version',
      label: 'Firmware Version',
      type: 'text',
      isRequired: true,
      isFilterable: true,
      isVisibleInList: true,
      sortOrder: 1,
      isActive: true,
      createdBy: adminUserId,
      updatedBy: adminUserId,
    },
    {
      id: customFieldIds.coolingType,
      key: 'cooling_type',
      label: 'Cooling Type',
      type: 'select',
      optionsJson: { options: ['air', 'liquid'] },
      isRequired: true,
      isFilterable: true,
      isVisibleInList: true,
      sortOrder: 2,
      isActive: true,
      createdBy: adminUserId,
      updatedBy: adminUserId,
    },
    {
      id: customFieldIds.networkProvider,
      key: 'network_provider',
      label: 'Network Provider',
      type: 'select',
      optionsJson: { options: ['LTE', 'Ethernet', 'WiFi'] },
      isRequired: false,
      isFilterable: true,
      isVisibleInList: false,
      sortOrder: 3,
      isActive: true,
      createdBy: adminUserId,
      updatedBy: adminUserId,
    },
    {
      id: customFieldIds.installationZone,
      key: 'installation_zone',
      label: 'Installation Zone',
      type: 'text',
      isRequired: false,
      isFilterable: true,
      isVisibleInList: true,
      sortOrder: 4,
      isActive: true,
      createdBy: adminUserId,
      updatedBy: adminUserId,
    },
    {
      id: customFieldIds.batteryBufferKwh,
      key: 'battery_buffer_kwh',
      label: 'Battery Buffer (kWh)',
      type: 'number',
      isRequired: false,
      isFilterable: true,
      isVisibleInList: false,
      sortOrder: 5,
      isActive: true,
      createdBy: adminUserId,
      updatedBy: adminUserId,
    },
    {
      id: customFieldIds.commissioningDate,
      key: 'commissioning_date',
      label: 'Commissioning Date',
      type: 'date',
      isRequired: false,
      isFilterable: true,
      isVisibleInList: false,
      sortOrder: 6,
      isActive: true,
      createdBy: adminUserId,
      updatedBy: adminUserId,
    },
  ]);

  await db.insert(stationBrands).values([
    { id: brandIds.vestel, name: 'Vestel', isActive: true },
  ]);

  await db.insert(stationModels).values([
    {
      id: modelIds.evc02,
      brandId: brandIds.vestel,
      name: 'EVC02',
      description: 'Single-socket AC charger with one Type2 connector and 22 kW output.',
      isActive: true,
    },
    {
      id: modelIds.evc04,
      brandId: brandIds.vestel,
      name: 'EVC04',
      description: 'AC charger with one Type2 connector and 22 kW output for site parking deployments.',
      isActive: true,
    },
    {
      id: modelIds.evc05,
      brandId: brandIds.vestel,
      name: 'EVC05',
      description: 'Dual Type2 AC charger with 2x22 kW connector layout.',
      isActive: true,
    },
    {
      id: modelIds.evc06,
      brandId: brandIds.vestel,
      name: 'EVC06',
      description: 'Hybrid DC platform with 2x Type2 AC, 1x CHAdeMO, and 1x CCS2 connectors.',
      isActive: true,
    },
  ]);

  await db.insert(stationModelConnectorTemplates).values([
    {
      modelId: modelIds.evc02,
      version: 1,
      connectorNo: 1,
      connectorType: 'Type2',
      currentType: 'AC',
      powerKw: '22.00',
      isActive: true,
      sortOrder: 1,
    },
    {
      modelId: modelIds.evc04,
      version: 1,
      connectorNo: 1,
      connectorType: 'Type2',
      currentType: 'AC',
      powerKw: '22.00',
      isActive: true,
      sortOrder: 1,
    },
    {
      modelId: modelIds.evc05,
      version: 1,
      connectorNo: 1,
      connectorType: 'Type2',
      currentType: 'AC',
      powerKw: '22.00',
      isActive: true,
      sortOrder: 1,
    },
    {
      modelId: modelIds.evc05,
      version: 1,
      connectorNo: 2,
      connectorType: 'Type2',
      currentType: 'AC',
      powerKw: '22.00',
      isActive: true,
      sortOrder: 2,
    },
    {
      modelId: modelIds.evc06,
      version: 1,
      connectorNo: 1,
      connectorType: 'Type2',
      currentType: 'AC',
      powerKw: '22.00',
      isActive: true,
      sortOrder: 1,
    },
    {
      modelId: modelIds.evc06,
      version: 1,
      connectorNo: 2,
      connectorType: 'Type2',
      currentType: 'AC',
      powerKw: '22.00',
      isActive: true,
      sortOrder: 2,
    },
    {
      modelId: modelIds.evc06,
      version: 1,
      connectorNo: 3,
      connectorType: 'CHAdeMO',
      currentType: 'DC',
      powerKw: '60.00',
      isActive: true,
      sortOrder: 3,
    },
    {
      modelId: modelIds.evc06,
      version: 1,
      connectorNo: 4,
      connectorType: 'CCS2',
      currentType: 'DC',
      powerKw: '180.00',
      isActive: true,
      sortOrder: 4,
    },
  ]);

  await db.insert(stations).values([
    {
      id: stationIds.s1,
      name: 'Istanbul HQ AC Bay 1',
      code: 'IST-RD-001',
      qrCode: 'QR-IST-RD-001',
      brandId: brandIds.vestel,
      modelId: modelIds.evc02,
      brand: 'Vestel',
      model: 'EVC02',
      serialNumber: 'VST-EVC02-0001',
      powerKw: '22.00',
      currentType: 'AC',
      socketType: 'Type2',
      location: 'Istanbul HQ - Test Hall A',
      status: 'active',
      lastTestDate: new Date('2026-03-22T09:30:00.000Z'),
      notes: 'Baseline single-port AC validation unit.',
      modelTemplateVersion: 1,
      createdBy: adminUserId,
      updatedBy: operatorUserId,
    },
    {
      id: stationIds.s2,
      name: 'Istanbul HQ AC Bay 2',
      code: 'IST-RD-002',
      qrCode: 'QR-IST-RD-002',
      brandId: brandIds.vestel,
      modelId: modelIds.evc04,
      brand: 'Vestel',
      model: 'EVC04',
      serialNumber: 'VST-EVC04-0002',
      powerKw: '22.00',
      currentType: 'AC',
      socketType: 'Type2',
      location: 'Istanbul HQ - Test Hall A',
      status: 'maintenance',
      lastTestDate: new Date('2026-03-18T11:00:00.000Z'),
      notes: 'Cabinet harness inspection in progress.',
      modelTemplateVersion: 1,
      createdBy: adminUserId,
      updatedBy: operatorUserId,
    },
    {
      id: stationIds.s3,
      name: 'Ankara Pilot Dual AC 1',
      code: 'ANK-PLT-001',
      qrCode: 'QR-ANK-PLT-001',
      brandId: brandIds.vestel,
      modelId: modelIds.evc05,
      brand: 'Vestel',
      model: 'EVC05',
      serialNumber: 'VST-EVC05-0101',
      powerKw: '22.00',
      currentType: 'AC',
      socketType: 'Type2',
      location: 'Ankara Pilot Site - Indoor Lab',
      status: 'active',
      lastTestDate: new Date('2026-03-20T07:10:00.000Z'),
      notes: null,
      modelTemplateVersion: 1,
      createdBy: adminUserId,
      updatedBy: adminUserId,
    },
    {
      id: stationIds.s4,
      name: 'Ankara Pilot Hybrid 1',
      code: 'ANK-PLT-002',
      qrCode: 'QR-ANK-PLT-002',
      brandId: brandIds.vestel,
      modelId: modelIds.evc06,
      brand: 'Vestel',
      model: 'EVC06',
      serialNumber: 'VST-EVC06-1501',
      powerKw: '180.00',
      currentType: 'DC',
      socketType: 'Type2, CHAdeMO, CCS2',
      location: 'Ankara Pilot Site - Outdoor Rig',
      status: 'faulty',
      lastTestDate: new Date('2026-03-14T14:45:00.000Z'),
      notes: 'DC output lane intermittently drops during peak session.',
      modelTemplateVersion: 1,
      createdBy: adminUserId,
      updatedBy: operatorUserId,
    },
    {
      id: stationIds.s5,
      name: 'Izmir Validation AC 1',
      code: 'IZM-VLD-001',
      qrCode: 'QR-IZM-VLD-001',
      brandId: brandIds.vestel,
      modelId: modelIds.evc02,
      brand: 'Vestel',
      model: 'EVC02',
      serialNumber: 'VST-EVC02-2201',
      powerKw: '22.00',
      currentType: 'AC',
      socketType: 'Type2',
      location: 'Izmir Validation Center',
      status: 'inactive',
      lastTestDate: new Date('2026-02-25T08:20:00.000Z'),
      notes: 'Reserved for firmware rollback tests.',
      modelTemplateVersion: null,
      createdBy: adminUserId,
      updatedBy: operatorUserId,
    },
    {
      id: stationIds.s6,
      name: 'Bursa Field Dual AC 1',
      code: 'BUR-FLD-001',
      qrCode: 'QR-BUR-FLD-001',
      brandId: brandIds.vestel,
      modelId: modelIds.evc05,
      brand: 'Vestel',
      model: 'EVC05',
      serialNumber: 'VST-EVC05-0441',
      powerKw: '22.00',
      currentType: 'AC',
      socketType: 'Type2',
      location: 'Bursa Field Garage',
      status: 'active',
      lastTestDate: new Date('2026-03-10T10:15:00.000Z'),
      notes: null,
      modelTemplateVersion: 1,
      createdBy: adminUserId,
      updatedBy: operatorUserId,
    },
    {
      id: stationIds.s7,
      name: 'Bursa Fleet Hub DC 1',
      code: 'BUR-FLD-002',
      qrCode: 'QR-BUR-FLD-002',
      brandId: brandIds.vestel,
      modelId: modelIds.evc06,
      brand: 'Vestel',
      model: 'EVC06',
      serialNumber: 'VST-EVC06-0662',
      powerKw: '180.00',
      currentType: 'DC',
      socketType: 'Type2, CHAdeMO, CCS2',
      location: 'Bursa Field Garage',
      status: 'active',
      lastTestDate: new Date('2026-03-19T16:00:00.000Z'),
      notes: 'Used for fleet endurance testing.',
      modelTemplateVersion: 1,
      createdBy: adminUserId,
      updatedBy: operatorUserId,
    },
    {
      id: stationIds.s8,
      name: 'Archived AC Unit',
      code: 'LEG-ARC-001',
      qrCode: 'QR-LEG-ARC-001',
      brandId: brandIds.vestel,
      modelId: modelIds.evc04,
      brand: 'Vestel',
      model: 'EVC04',
      serialNumber: 'VST-EVC04-0009',
      powerKw: '22.00',
      currentType: 'AC',
      socketType: 'Type2',
      location: 'Istanbul Storage Depot',
      status: 'inactive',
      isArchived: true,
      archivedAt: new Date('2025-12-01T09:00:00.000Z'),
      lastTestDate: new Date('2025-11-20T10:00:00.000Z'),
      notes: 'Archived after decommissioning.',
      modelTemplateVersion: null,
      createdBy: adminUserId,
      updatedBy: adminUserId,
    },
  ]);

  await db.insert(stationConnectors).values([
    {
      id: 'abababab-0000-0000-0000-000000000001',
      stationId: stationIds.s1,
      connectorNo: 1,
      connectorType: 'Type2',
      currentType: 'AC',
      powerKw: '22.00',
      isActive: true,
      sortOrder: 1,
      isDeleted: false,
      deletedAt: null,
    },
    {
      id: 'abababab-0000-0000-0000-000000000002',
      stationId: stationIds.s2,
      connectorNo: 1,
      connectorType: 'Type2',
      currentType: 'AC',
      powerKw: '22.00',
      isActive: true,
      sortOrder: 1,
      isDeleted: false,
      deletedAt: null,
    },
    {
      id: 'abababab-0000-0000-0000-000000000003',
      stationId: stationIds.s3,
      connectorNo: 1,
      connectorType: 'Type2',
      currentType: 'AC',
      powerKw: '22.00',
      isActive: true,
      sortOrder: 1,
      isDeleted: false,
      deletedAt: null,
    },
    {
      id: 'abababab-0000-0000-0000-000000000004',
      stationId: stationIds.s3,
      connectorNo: 2,
      connectorType: 'Type2',
      currentType: 'AC',
      powerKw: '22.00',
      isActive: true,
      sortOrder: 2,
      isDeleted: false,
      deletedAt: null,
    },
    {
      id: 'abababab-0000-0000-0000-000000000005',
      stationId: stationIds.s4,
      connectorNo: 1,
      connectorType: 'Type2',
      currentType: 'AC',
      powerKw: '22.00',
      isActive: true,
      sortOrder: 1,
      isDeleted: false,
      deletedAt: null,
    },
    {
      id: 'abababab-0000-0000-0000-000000000006',
      stationId: stationIds.s4,
      connectorNo: 2,
      connectorType: 'Type2',
      currentType: 'AC',
      powerKw: '22.00',
      isActive: true,
      sortOrder: 2,
      isDeleted: false,
      deletedAt: null,
    },
    {
      id: 'abababab-0000-0000-0000-000000000007',
      stationId: stationIds.s4,
      connectorNo: 3,
      connectorType: 'CHAdeMO',
      currentType: 'DC',
      powerKw: '60.00',
      isActive: true,
      sortOrder: 3,
      isDeleted: false,
      deletedAt: null,
    },
    {
      id: 'abababab-0000-0000-0000-000000000008',
      stationId: stationIds.s4,
      connectorNo: 4,
      connectorType: 'CCS2',
      currentType: 'DC',
      powerKw: '180.00',
      isActive: true,
      sortOrder: 4,
      isDeleted: false,
      deletedAt: null,
    },
    {
      id: 'abababab-0000-0000-0000-000000000009',
      stationId: stationIds.s5,
      connectorNo: 1,
      connectorType: 'Type2',
      currentType: 'AC',
      powerKw: '22.00',
      isActive: true,
      sortOrder: 1,
      isDeleted: false,
      deletedAt: null,
    },
    {
      id: 'abababab-0000-0000-0000-000000000010',
      stationId: stationIds.s6,
      connectorNo: 1,
      connectorType: 'Type2',
      currentType: 'AC',
      powerKw: '22.00',
      isActive: true,
      sortOrder: 1,
      isDeleted: false,
      deletedAt: null,
    },
    {
      id: 'abababab-0000-0000-0000-000000000011',
      stationId: stationIds.s6,
      connectorNo: 2,
      connectorType: 'Type2',
      currentType: 'AC',
      powerKw: '22.00',
      isActive: true,
      sortOrder: 2,
      isDeleted: false,
      deletedAt: null,
    },
    {
      id: 'abababab-0000-0000-0000-000000000012',
      stationId: stationIds.s7,
      connectorNo: 1,
      connectorType: 'Type2',
      currentType: 'AC',
      powerKw: '22.00',
      isActive: true,
      sortOrder: 1,
      isDeleted: false,
      deletedAt: null,
    },
    {
      id: 'abababab-0000-0000-0000-000000000013',
      stationId: stationIds.s7,
      connectorNo: 2,
      connectorType: 'Type2',
      currentType: 'AC',
      powerKw: '22.00',
      isActive: true,
      sortOrder: 2,
      isDeleted: false,
      deletedAt: null,
    },
    {
      id: 'abababab-0000-0000-0000-000000000014',
      stationId: stationIds.s7,
      connectorNo: 3,
      connectorType: 'CHAdeMO',
      currentType: 'DC',
      powerKw: '60.00',
      isActive: true,
      sortOrder: 3,
      isDeleted: false,
      deletedAt: null,
    },
    {
      id: 'abababab-0000-0000-0000-000000000015',
      stationId: stationIds.s7,
      connectorNo: 4,
      connectorType: 'CCS2',
      currentType: 'DC',
      powerKw: '180.00',
      isActive: true,
      sortOrder: 4,
      isDeleted: false,
      deletedAt: null,
    },
    {
      id: 'abababab-0000-0000-0000-000000000016',
      stationId: stationIds.s8,
      connectorNo: 1,
      connectorType: 'Type2',
      currentType: 'AC',
      powerKw: '22.00',
      isActive: true,
      sortOrder: 1,
      isDeleted: false,
      deletedAt: null,
    },
  ]);

  const values = [
    [stationIds.s1, customFieldIds.firmwareVersion, 'v3.2.7'],
    [stationIds.s1, customFieldIds.coolingType, 'liquid'],
    [stationIds.s1, customFieldIds.networkProvider, 'Ethernet'],
    [stationIds.s1, customFieldIds.installationZone, 'A-01'],
    [stationIds.s1, customFieldIds.batteryBufferKwh, 5.5],
    [stationIds.s1, customFieldIds.commissioningDate, '2025-03-01'],

    [stationIds.s2, customFieldIds.firmwareVersion, 'v3.1.9'],
    [stationIds.s2, customFieldIds.coolingType, 'liquid'],
    [stationIds.s2, customFieldIds.networkProvider, 'LTE'],
    [stationIds.s2, customFieldIds.installationZone, 'A-02'],

    [stationIds.s3, customFieldIds.firmwareVersion, 'v2.0.4'],
    [stationIds.s3, customFieldIds.coolingType, 'air'],
    [stationIds.s3, customFieldIds.networkProvider, 'WiFi'],
    [stationIds.s3, customFieldIds.installationZone, 'B-11'],
    [stationIds.s3, customFieldIds.commissioningDate, '2024-10-17'],

    [stationIds.s4, customFieldIds.firmwareVersion, 'v4.0.1'],
    [stationIds.s4, customFieldIds.coolingType, 'liquid'],
    [stationIds.s4, customFieldIds.networkProvider, 'Ethernet'],
    [stationIds.s4, customFieldIds.installationZone, 'B-12'],

    [stationIds.s5, customFieldIds.firmwareVersion, 'v1.9.5'],
    [stationIds.s5, customFieldIds.coolingType, 'air'],
    [stationIds.s5, customFieldIds.installationZone, 'C-02'],

    [stationIds.s6, customFieldIds.firmwareVersion, 'v2.7.0'],
    [stationIds.s6, customFieldIds.coolingType, 'air'],
    [stationIds.s6, customFieldIds.networkProvider, 'LTE'],
    [stationIds.s6, customFieldIds.installationZone, 'F-01'],

    [stationIds.s7, customFieldIds.firmwareVersion, 'v3.0.8'],
    [stationIds.s7, customFieldIds.coolingType, 'liquid'],
    [stationIds.s7, customFieldIds.networkProvider, 'Ethernet'],
    [stationIds.s7, customFieldIds.installationZone, 'F-02'],

    [stationIds.s8, customFieldIds.firmwareVersion, 'v1.2.0'],
    [stationIds.s8, customFieldIds.coolingType, 'air'],
    [stationIds.s8, customFieldIds.installationZone, 'ARCHIVE'],
  ] as const;

  await db.insert(stationCustomFieldValues).values(
    values.map(([stationId, fieldDefinitionId, valueJson], index) => ({
      id: `cccccccc-0000-0000-0000-${(index + 1).toString().padStart(12, '0')}`,
      stationId,
      fieldDefinitionId,
      valueJson,
    })),
  );

  await db.insert(stationTestHistory).values([
    {
      id: 'dddddddd-0000-0000-0000-000000000001',
      stationId: stationIds.s1,
      testDate: new Date('2026-03-22T09:30:00.000Z'),
      result: 'pass',
      notes: 'AC charging session passed at nominal 22 kW output.',
      metricsJson: { peakCurrentA: 32, temperatureC: 38.4 },
      testedBy: operatorUserId,
    },
    {
      id: 'dddddddd-0000-0000-0000-000000000002',
      stationId: stationIds.s1,
      testDate: new Date('2026-03-10T09:00:00.000Z'),
      result: 'warning',
      notes: 'Minor AC handshake delay observed on first session.',
      metricsJson: { handshakeMs: 890 },
      testedBy: operatorUserId,
    },
    {
      id: 'dddddddd-0000-0000-0000-000000000003',
      stationId: stationIds.s2,
      testDate: new Date('2026-03-18T11:00:00.000Z'),
      result: 'fail',
      notes: 'Input harness insulation warning triggered during soak test.',
      metricsJson: { insulationAlarmCount: 3 },
      testedBy: operatorUserId,
    },
    {
      id: 'dddddddd-0000-0000-0000-000000000004',
      stationId: stationIds.s3,
      testDate: new Date('2026-03-20T07:10:00.000Z'),
      result: 'pass',
      notes: 'Both AC outputs sustained stable charging profile.',
      metricsJson: { handshakeMs: 410, dualSessionPass: true },
      testedBy: operatorUserId,
    },
    {
      id: 'dddddddd-0000-0000-0000-000000000005',
      stationId: stationIds.s4,
      testDate: new Date('2026-03-14T14:45:00.000Z'),
      result: 'fail',
      notes: 'Contactor did not close consistently.',
      metricsJson: { failureRate: 0.38 },
      testedBy: adminUserId,
    },
    {
      id: 'dddddddd-0000-0000-0000-000000000006',
      stationId: stationIds.s7,
      testDate: new Date('2026-03-19T16:00:00.000Z'),
      result: 'pass',
      notes: 'Hybrid DC/AC fleet session passed for 6-hour endurance run.',
      metricsJson: { avgPowerKw: 74.6, dcSessionCount: 18 },
      testedBy: operatorUserId,
    },
  ]);

  await db.insert(stationIssueRecords).values([
    {
      id: 'eeeeeeee-0000-0000-0000-000000000001',
      stationId: stationIds.s2,
      title: 'Input harness inspection pending closure',
      description: 'Insulation warning was triggered during the latest soak test and requires wiring verification.',
      severity: 'high',
      status: 'in_progress',
      reportedBy: operatorUserId,
      assignedTo: adminUserId,
    },
    {
      id: 'eeeeeeee-0000-0000-0000-000000000002',
      stationId: stationIds.s4,
      title: 'DC output drop during peak charging test',
      description: 'Hybrid station drops the DC lane intermittently under repeated high-load attempts.',
      severity: 'critical',
      status: 'open',
      reportedBy: adminUserId,
      assignedTo: operatorUserId,
    },
    {
      id: 'eeeeeeee-0000-0000-0000-000000000003',
      stationId: stationIds.s5,
      title: 'Firmware rollback verification pending',
      description: 'Station held inactive until rollback validation completes.',
      severity: 'medium',
      status: 'open',
      reportedBy: operatorUserId,
      assignedTo: operatorUserId,
    },
    {
      id: 'eeeeeeee-0000-0000-0000-000000000004',
      stationId: stationIds.s7,
      title: 'Intermittent LTE signal drop',
      description: 'Short network disconnect events were observed during the overnight fleet cycle.',
      severity: 'low',
      status: 'resolved',
      resolvedAt: new Date('2026-03-21T02:15:00.000Z'),
      reportedBy: operatorUserId,
      assignedTo: operatorUserId,
    },
  ]);

  await db.insert(auditLogs).values({
    id: 'ffffffff-0000-0000-0000-000000000001',
    actorUserId: adminUserId,
    entityType: 'seed',
    entityId: adminUserId,
    action: 'db.seed.completed',
    metadataJson: {
      users: 2,
      stations: 8,
      customFields: 6,
      testHistoryRecords: 6,
      issueRecords: 4,
    },
  });
};

seed()
  .then(async () => {
    console.log('Seed data inserted successfully.');
    await pool.end();
  })
  .catch(async (error) => {
    console.error('Seed failed:', error);
    await pool.end();
    process.exit(1);
  });
